'use client';

import React, { useState, useEffect } from 'react';
import { CSGOSkin, Layer } from '../types';

interface OverlaySystemProps {
    skin: CSGOSkin | undefined;
    layers: Layer[];
    selectedId: string | null;
    fonts: string[];
    onLayersChange: (layers: Layer[]) => void;
    onUpdateLayer: (id: string, updates: Partial<Layer>) => void;
    onDeleteLayer: (id: string) => void;
    compactMode?: boolean;
}

type TemplateType = 'minimal' | 'retail' | 'esports' | 'engagement' | 'postmatch' | 'versus';

const TEMPLATE_LABELS: Record<TemplateType, string> = {
    minimal: '🎯 Minimal',
    retail: '💰 Retail',
    esports: '🏆 Esports',
    engagement: '💬 Engagement',
    postmatch: '❓ Post-Match',
    versus: '⚔️ VS Float',
};

export const OverlaySystem: React.FC<OverlaySystemProps> = ({
    skin, layers, selectedId, fonts,
    onLayersChange, onUpdateLayer, onDeleteLayer
}) => {
    const [template, setTemplate] = useState<TemplateType>('minimal');

    // Retail
    const [customPrice, setCustomPrice] = useState('');
    const [customFloat, setCustomFloat] = useState('0.001 FN');

    // Post-Match
    const [pmQuestion, setPmQuestion] = useState('E aí?');
    const [pmSub, setPmSub] = useState('Como foi\na partida?');

    // Versus
    const [vsTitle, setVsTitle] = useState('Float, Condition e Detalhe.');
    const [vsLabelA, setVsLabelA] = useState('LADO A');
    const [vsDescA, setVsDescA] = useState('Um pouco\ndesgastado...');
    const [vsLabelB, setVsLabelB] = useState('LADO B');
    const [vsDescB, setVsDescB] = useState('Perfeita!');

    // Engagement
    const [engQuestion, setEngQuestion] = useState('');
    const [engSub, setEngSub] = useState('Comenta a skin que pra você é mais top!');

    const selected = layers.find(l => l.id === selectedId);

    // Helpers to create text layers
    const createTextLayer = (id: string, text: string, x: number, y: number, style: any, zIndex: number): Layer => ({
        id,
        type: 'text',
        text,
        x,
        y,
        rotation: style.rotation || 0,
        scale: 1,
        zIndex,
        opacity: 1,
        visible: true,
        locked: false,
        style: {
            fontFamily: style.fontFamily,
            fontWeight: style.fontWeight,
            fontSize: style.fontSize,
            color: style.color,
            textAlign: style.textAlign,
            shadow: true
        }
    });

    useEffect(() => {
        if (!skin) return;

        // Keep non-text layers (images) and existing text layers that are NOT part of the template system?
        // Or replace ALL text layers? 
        // For simplicity, let's keep image layers and replace text layers generated by this system. 
        // But tracking which ones are template-generated is hard without IDs.
        // Let's assume template change RESETS the text layers for now, preserving images.

        const existingImages = layers.filter(l => l.type !== 'text');

        // If current layers are manually edited, maybe we shouldn't overwrite? 
        // But the user clicked a template button implies overwrite intent.

        let newLayers: Layer[] = [...existingImages];
        const baseId = Date.now();
        const safeName = skin.name.toUpperCase();
        const weaponName = skin.weapon.name.toUpperCase();
        let z = 100; // Text on top

        if (template === 'minimal') {
            newLayers.push(
                createTextLayer(`t-${baseId}-1`, safeName, 50, 90, { fontSize: 42, color: '#ffffff', fontFamily: 'Oswald', fontWeight: '900', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-2`, weaponName, 50, 82, { fontSize: 16, color: '#F97316', fontFamily: 'Inter', fontWeight: '700', textAlign: 'center' }, z++)
            );
        } else if (template === 'retail') {
            newLayers.push(
                createTextLayer(`t-${baseId}-1`, safeName, 50, 15, { fontSize: 32, color: '#ffffff', fontFamily: 'Oswald', fontWeight: '900', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-2`, customPrice || 'R$ 00,00', 85, 85, { fontSize: 48, color: '#22c55e', fontFamily: 'Inter', fontWeight: '900', textAlign: 'right' }, z++),
                createTextLayer(`t-${baseId}-3`, `FLOAT: ${customFloat}`, 85, 92, { fontSize: 12, color: '#cbd5e1', fontFamily: 'Inter', fontWeight: '500', textAlign: 'right' }, z++)
            );
        } else if (template === 'esports') {
            newLayers.push(
                createTextLayer(`t-${baseId}-1`, 'OFFICIAL DROP', 50, 10, { fontSize: 14, color: '#F97316', fontFamily: 'Inter', fontWeight: '900', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-2`, safeName, 50, 50, { fontSize: 64, color: 'rgba(255,255,255,0.1)', fontFamily: 'Oswald', fontWeight: '900', textAlign: 'center' }, z++)
            );
        } else if (template === 'engagement') {
            const question = engQuestion || `E você, teria uma ${skin.weapon.name}?`;
            newLayers.push(
                createTextLayer(`t-${baseId}-1`, question, 50, 68, { fontSize: 30, color: '#ffffff', fontFamily: 'Oswald', fontWeight: '900', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-2`, engSub, 50, 82, { fontSize: 13, color: '#cbd5e1', fontFamily: 'Inter', fontWeight: '400', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-brand`, 'CS AD-PRO', 50, 93, { fontSize: 11, color: '#8b5cf6', fontFamily: 'Oswald', fontWeight: '700', textAlign: 'center' }, z++)
            );
        } else if (template === 'postmatch') {
            newLayers.push(
                createTextLayer(`t-${baseId}-1`, `? ${pmQuestion}`, 22, 20, { rotation: -8, fontSize: 56, color: '#ffffff', fontFamily: 'Oswald', fontWeight: '900', textAlign: 'left' }, z++),
                createTextLayer(`t-${baseId}-2`, pmSub, 22, 42, { rotation: -5, fontSize: 40, color: '#FACC15', fontFamily: 'Oswald', fontWeight: '900', textAlign: 'left' }, z++)
            );
        } else if (template === 'versus') {
            newLayers.push(
                createTextLayer(`t-${baseId}-title`, vsTitle, 50, 8, { fontSize: 22, color: '#ffffff', fontFamily: 'Inter', fontWeight: '700', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-la`, vsLabelA, 22, 28, { fontSize: 22, color: '#ffffff', fontFamily: 'Inter', fontWeight: '900', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-da`, vsDescA, 22, 40, { fontSize: 14, color: '#cbd5e1', fontFamily: 'Inter', fontWeight: '400', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-vs`, 'VS', 50, 52, { fontSize: 44, color: '#F97316', fontFamily: 'Oswald', fontWeight: '900', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-lb`, vsLabelB, 78, 28, { fontSize: 22, color: '#ffffff', fontFamily: 'Inter', fontWeight: '900', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-db`, vsDescB, 78, 40, { fontSize: 14, color: '#FACC15', fontFamily: 'Inter', fontWeight: '700', textAlign: 'center' }, z++),
                createTextLayer(`t-${baseId}-brand`, 'CS AD-PRO', 50, 93, { fontSize: 14, color: '#8b5cf6', fontFamily: 'Oswald', fontWeight: '700', textAlign: 'center' }, z++)
            );
        }

        onLayersChange(newLayers);
    }, [skin, template, customPrice, customFloat, pmQuestion, pmSub, vsTitle, vsLabelA, vsDescA, vsLabelB, vsDescB, engQuestion, engSub]);

    const inputCls = 'w-full bg-zinc-950 border border-zinc-800 rounded px-2 py-1.5 text-[11px] text-white outline-none focus:border-orange-600 transition-colors';

    return (
        <div className="bg-zinc-900/50 p-4 rounded-xl border border-zinc-800 space-y-4">
            {/* Template Selector */}
            <div className="space-y-2">
                <label className="text-[10px] font-black uppercase text-zinc-500">Template</label>
                <div className="grid grid-cols-2 gap-1.5">
                    {(Object.keys(TEMPLATE_LABELS) as TemplateType[]).map(t => (
                        <button
                            key={t}
                            onClick={() => setTemplate(t)}
                            className={`px-2 py-2 text-[9px] uppercase font-bold rounded border transition-all text-left ${template === t ? 'bg-orange-600 text-white border-orange-500' : 'bg-zinc-950 text-zinc-400 border-zinc-800 hover:border-zinc-600'}`}
                        >
                            {TEMPLATE_LABELS[t]}
                        </button>
                    ))}
                </div>
            </div>

            {/* Template-specific inputs */}
            {template === 'retail' && (
                <div className="space-y-2 animate-in fade-in">
                    <label className="text-[10px] font-black uppercase text-zinc-500">Customizar</label>
                    <input type="text" placeholder="Preço (ex: R$ 1.200,00)" value={customPrice} onChange={e => setCustomPrice(e.target.value)} className={inputCls} />
                    <input type="text" placeholder="Float (ex: 0.001 FN)" value={customFloat} onChange={e => setCustomFloat(e.target.value)} className={inputCls} />
                </div>
            )}

            {template === 'postmatch' && (
                <div className="space-y-2 animate-in fade-in">
                    <label className="text-[10px] font-black uppercase text-zinc-500">Customizar</label>
                    <input type="text" placeholder="Pergunta (ex: E aí?)" value={pmQuestion} onChange={e => setPmQuestion(e.target.value)} className={inputCls} />
                    <textarea placeholder="Subtítulo" value={pmSub} onChange={e => setPmSub(e.target.value)} className={`${inputCls} h-16 resize-none`} />
                </div>
            )}

            {template === 'versus' && (
                <div className="space-y-2 animate-in fade-in">
                    <label className="text-[10px] font-black uppercase text-zinc-500">Customizar</label>
                    <input type="text" placeholder="Título" value={vsTitle} onChange={e => setVsTitle(e.target.value)} className={inputCls} />
                    <div className="grid grid-cols-2 gap-2">
                        <div className="space-y-1">
                            <span className="text-[9px] text-zinc-500 uppercase font-bold">Lado A</span>
                            <input type="text" placeholder="Label A" value={vsLabelA} onChange={e => setVsLabelA(e.target.value)} className={inputCls} />
                            <textarea placeholder="Descrição A" value={vsDescA} onChange={e => setVsDescA(e.target.value)} className={`${inputCls} h-14 resize-none`} />
                        </div>
                        <div className="space-y-1">
                            <span className="text-[9px] text-zinc-500 uppercase font-bold">Lado B</span>
                            <input type="text" placeholder="Label B" value={vsLabelB} onChange={e => setVsLabelB(e.target.value)} className={inputCls} />
                            <textarea placeholder="Descrição B" value={vsDescB} onChange={e => setVsDescB(e.target.value)} className={`${inputCls} h-14 resize-none`} />
                        </div>
                    </div>
                </div>
            )}

            {template === 'engagement' && (
                <div className="space-y-2 animate-in fade-in">
                    <label className="text-[10px] font-black uppercase text-zinc-500">Customizar</label>
                    <textarea placeholder={`E você, teria uma ${skin?.weapon.name || 'skin'}?`} value={engQuestion} onChange={e => setEngQuestion(e.target.value)} className={`${inputCls} h-16 resize-none`} />
                    <input type="text" placeholder="Subtítulo" value={engSub} onChange={e => setEngSub(e.target.value)} className={inputCls} />
                </div>
            )}
        </div>
    );
};
